language: php

sudo: false

php:
  - "7.1"
  - "7.2"

services:
  - docker

before_install:
  - docker-compose up -d
  - docker ps -a
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --colors=always --configuration phpunit.xml

after_script:
  - docker-compose down -v
